# Generated by Django 3.2.4 on 2021-06-19 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'スクールデータ', 'verbose_name_plural': 'スクールデータ'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生データ', 'verbose_name_plural': '学生データ'},
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, verbose_name='スクール名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('秀', '秀'), ('優', '優'), ('良', '良'), ('可', '可'), ('不', '不')], max_length=5, verbose_name='成績'),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school', verbose_name='スクール名'),
        ),
    ]
